<a href="https://colab.research.google.com/github/tabaahi07/Deep-Learning/blob/main/Numpy_array_as_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np

In [21]:
from re import X
# Numpy array can act as a matrix and perform matrix operations
x = np.array([[1,2,3] , [2,1,1] , [3,7,5]])
y = np.array([[8,0,1] , [1,0,0] , [5,6,2]])
x

array([[1, 2, 3],
       [2, 1, 1],
       [3, 7, 5]])

In [22]:
# Matrix substraction
p = x-y
p

array([[-7,  2,  2],
       [ 1,  1,  1],
       [-2,  1,  3]])

In [23]:
# Ele to ele multiplication
multi = x * y
multi

array([[ 8,  0,  3],
       [ 2,  0,  0],
       [15, 42, 10]])

In [24]:
# Matrix dot product
np.dot(x , y)

array([[25, 18,  7],
       [22,  6,  4],
       [56, 30, 13]])

In [25]:
# cross product
np.cross(x , y)

array([[  2,  23, -16],
       [  0,   1,  -1],
       [-16,  19, -17]])